name = "BiologicalOscillations"
uuid = "127c734c-d51c-490b-a01e-6a0ce858f88d"
authors = ["Franco Tavella"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
