pages = Any["Home" => "index.md",
            "Protein Interaction Networks" => Any["protein_interaction_network/pin_introduction.md", 
                                                  "protein_interaction_network/pin_model_details.md",
                                                  "protein_interaction_network/pin_documentation.md"],
            "Gene Regulatory Networks" => Any["gene_regulatory_network/grn_introduction.md", 
                                              "gene_regulatory_network/grn_model_details.md", 
                                              "gene_regulatory_network/grn_documentation.md"],
            "Feature Calculation" => Any["feature_calculation/fc_introduction.md"],
            "Models" => Any["models/elowitz_2000.md"],
]