name: Branch for visualization
on:
  push:
    branches:
      - main

permissions:
  contents: write

env:
  BRANCH_NAME: auto/viz

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Merge from main branch
        run: |
          git config user.name "Github Actions"
          git config user.email ""
          git checkout main
          git pull
          git checkout ${{ env.BRANCH_NAME }}
          git merge --allow-unrelated-histories --no-ff origin/main -m "Merge into viz branch"
          git push -u origin ${{ env.BRANCH_NAME }}
